# Generated by Django 3.1.7 on 2021-07-19 01:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
